### ISSUE TITLE
license files missing

### ISSUE THREAD

**Issue by dvzrv** [AudioSceneDescriptionFormat/asdf-rust#37]
Hi! :wave: 

I'm currently trying to build this project for Arch Linux, since I need it for updating ssr (FWIW, a feature level release would probably have been more appropriate for integrating a new library).
Unfortunately, I am missing the license files for this project. I definitely need the MIT license file as it usually contains data which makes it unique.

**Comment by mgeier** [comment]
Sorry for my late response!

I'm not sure if adding the license text is legally necessary, since both the README and the `Cargo.toml` already contain the SPDX codes.

The Rust Book says (https://doc.rust-lang.org/book/ch14-02-publishing-to-crates-io.html#adding-metadata-to-a-new-crate):

"If you want to use a license that doesn’t appear in the SPDX, you need to place the text of that license in a file, include the file in your project, and then use `license-file` to specify the name of that file instead of using the `license` key."

But if you really need it, I have created #42, which copies the files from the Rust project.

> I definitely need the MIT license file as it usually contains data which makes it unique.

The one from #42 doesn't make it unique, it's identical to the one from the Rust project.
There have been some discussions about the unique part here: https://github.com/rust-lang/rust/pull/43498

**Comment by mgeier** [comment]
License texts have been added in #42.
